'use client';

import { useState } from 'react';

const capabilities = [
  { title: 'Content platforms', number: '01', type: 'Professional practice', technologies: ['AEM', 'Sling Models', 'Content Fragments'], description: 'An authoring system has two audiences: the person publishing and the person reading. I work with components, content fragments, MSM, and dispatcher configuration so those needs fit together.', decision: 'Build reusable content structures and document how to author them. The editor experience is part of the engineering work.', link: '/resume', linkText: 'Read the professional experience' },
  { title: 'Front-end engineering', number: '02', type: 'Professional + independent practice', technologies: ['React', 'TypeScript', 'Jest'], description: 'Interfaces built from Figma designs, with attention to state, accessibility, and the small failures that users notice. React and TypeScript give that interaction a structure.', decision: 'Keep the readable interface independent of its visual effects. This portfolio’s content and routes remain usable when graphics are unavailable.', link: '/work/chroma-loop', linkText: 'Inspect an interaction project' },
  { title: 'Services & delivery', number: '03', type: 'Professional practice', technologies: ['Java', 'Node.js', 'Docker', 'AWS'], description: 'Spring Boot and Node services connect content to the interface. REST, GraphQL, and Pub/Sub are useful when their boundaries are clear; delivery and testing are part of the same system.', decision: 'Treat deployment configuration, testing, and secret scanning as normal delivery work. Public experiments show a smaller slice of that practice.', link: '/work/java-native-rag', linkText: 'Inspect the retrieval service' },
  { title: 'Graphics & retrieval', number: '04', type: 'Independent experiments', technologies: ['Three.js', 'Canvas', 'Spring AI'], description: 'A place to explore spatial interfaces, browser interaction, and questions over documents. These are independent experiments with visible source and clearly stated limits.', decision: 'Use inspectable prototypes to test an idea. A diagram explains retrieval; source and evaluation are needed to assess the answers.', link: '/work/java-native-rag', linkText: 'Explore the retrieval experiment' },
];

export default function CapabilityExhibit() {
  const [selected, setSelected] = useState(0);
  const item = capabilities[selected];
  return <div className="capability-exhibit"><div className="capability-map"><div className="system-core" aria-hidden="true"><span>V</span><small>THE PRACTICE</small></div><svg className="system-connections" viewBox="0 0 650 480" preserveAspectRatio="none" aria-hidden="true"><path d="M325 240 150 100M325 240 500 100M325 240 150 380M325 240 500 380" fill="none" stroke="#62686c" strokeWidth="1" /><path d={['M325 240 150 100', 'M325 240 500 100', 'M325 240 150 380', 'M325 240 500 380'][selected]} fill="none" stroke="#EEAE62" strokeWidth="2" /></svg><div className="capability-nodes" aria-label="Areas of practice">{capabilities.map((capability, i) => <button key={capability.title} className={`capability-node node-${i}`} type="button" aria-pressed={selected === i} aria-controls="capability-detail" onClick={() => setSelected(i)}><span className="node-number">{capability.number}</span><strong>{capability.title}</strong><span className="node-dot" aria-hidden="true" /></button>)}</div><p className="map-caption">Select a part. See how it connects.</p></div><div className="capability-detail" id="capability-detail" aria-live="polite"><p className="eyebrow">{item.type}</p><h3>{item.title}</h3><p>{item.description}</p><div className="decision-note"><span className="eyebrow">A working principle</span><p>{item.decision}</p></div><ul className="project-tags">{item.technologies.map(tech => <li key={tech}>{tech}</li>)}</ul><a className="action-link" href={item.link}>{item.linkText} <span aria-hidden="true">↗</span></a></div><details className="capability-text"><summary>Read all areas of practice</summary>{capabilities.map(capability => <div key={capability.title}><h3>{capability.title}</h3><p>{capability.description}</p><p>{capability.decision}</p><a className="text-link" href={capability.link}>{capability.linkText} ↗</a></div>)}</details></div>;
}
